### ISSUE TITLE
Test API credentials are not working.

### ISSUE THREAD

**Issue by netstartergit** [mochilafulfillment/mochila-api#2]
I have tried to connect to testing API using given credentials. But it fails.
"client_id":"12345678909876543212",
"apikey":"6421b93abcd7879fc41234719ff1b4d9",
```
{"success":false,"error_code":"AUTH","error":"Authorization Failure. ID: 209327"}
```
How do I connect to testing API?

**Comment by jtmochila** [comment]
Hi There,

We did not publish real credentials in the git docs. Credentials to a
sandbox environment are usually obtained from us as part of a new client
onboarding service. Are you a new client of Mochila or working with a new
client of Mochila? Please let us know what merchant you are associated with
and we can get you started. Also, I can provide you with a means of
creating new catalog items via the API, but please be aware that item
creation is not instanteous, but rather subject to review by Mochila admins
as a precaution.

Thanks,
JT

**Comment by netstartergit** [comment]
Hi, Thanks for the response. Yes, we are working with a new client of Mochila.
We have informed the client.
